# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_auto_20171214_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visits', models.IntegerField()),
                ('customerID', models.IntegerField(default=0)),
                ('is_staff', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'User Visits',
            },
        ),
    ]
