# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_uservisits'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserVisits',
        ),
    ]
