# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 17:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_uservisits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('visit', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='uservisits',
            name='date',
        ),
        migrations.AddField(
            model_name='dates',
            name='customerID',
            field=models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.CASCADE, to='store.UserVisits'),
        ),
        migrations.AlterUniqueTogether(
            name='dates',
            unique_together=set([('customerID', 'date')]),
        ),
    ]
