# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20171218_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='visit',
        ),
    ]
