# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_dates_visit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dates',
            options={'verbose_name_plural': 'Dates'},
        ),
        migrations.AlterUniqueTogether(
            name='dates',
            unique_together=set([]),
        ),
    ]
