# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20171218_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dates',
            name='customerID',
        ),
        migrations.AddField(
            model_name='customers',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.DeleteModel(
            name='UserVisits',
        ),
    ]
