# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20171221_1305'),
        ('store', '0023_auto_20180106_1813'),
    ]

    operations = [
    ]
