# Generated by Django 2.0.1 on 2018-01-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20180116_2237'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='customerID',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='prodNum',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
