# Generated by Django 2.0.1 on 2018-01-16 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20180116_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='customerID',
            field=models.ForeignKey(db_column='customerID', on_delete=django.db.models.deletion.CASCADE, to='store.Customers'),
        ),
    ]
